language: php

php: 7.4

before_script:
  - cp phpunit.travis.xml phpunit.xml
  - travis_retry composer self-update
  - travis_retry composer install --prefer-source --no-interaction
  - wget https://github.com/infection/infection/releases/download/0.17.0/infection.phar
  - wget https://github.com/infection/infection/releases/download/0.17.0/infection.phar.asc
  - gpg --recv-keys C6D76C329EBADE2FB9C458CFC5095986493B4AA0
  - gpg --with-fingerprint --verify infection.phar.asc infection.phar
  - chmod +x infection.phar

jobs:
  include:
    - stage: Infection
      script: ./infection.phar --min-msi=48 --threads=4
    - stage: CodeSniffer
      script: composer phpcbf && composer phpcs
    - stage: tests
      script: vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
