language: php

php: 7.4

before_script:
  - cp phpunit.travis.xml phpunit.xml
  - travis_retry composer self-update
  - travis_retry composer install --prefer-source --no-interaction

jobs:
  include:
    - stage: CodeSniffer
      script: composer phpcbf && composer phpcs
    - stage: tests
      script: vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
